add_newline = false

format = "ğŸ“ $directory$git_branch$git_status $nodejs$python $character"

[directory]
style = "none"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = " î‚  $branch"
style = "none"

[git_status]
format = " $all_status$ahead_behind"
style = "none"

[nodejs]
format = " îœ˜ $version"
style = "none"

[python]
format = " îˆµ $version"
style = "none"

[character]
success_symbol = "â¯ "
error_symbol = "â¯ "